class EventSignal:
    CHECK_PLANTS = "CHECK_PLANTS"
    REQUEST_MOISTURE_MEASUREMENTS = "REQUEST_MOISTURE_MEASUREMENTS"
    MOISTURE_MEASUREMENT_RESULTS = "MOISTURE_MEASUREMENT_RESULTS"
    UPDATE_DISPLAY = "UPDATE_DISPLAY"
